name: Build IV-Zero
on: 
 - push
 - pull_request
jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: arduino/compile-sketches@v1
      with:
        sketch-paths: |
         - ./
        platforms: |
          - name: "MiniCore"
          - source-url: https://github.com/MCUdude/MiniCore.git
        fqbn: "MiniCore:avr:48:bootloader=false,variant=modelP,BOD=2v7,LTO=Os,clock=16MHz_external"
        libraries: |
          - name: OneWire
          - source-url: https://github.com/PaulStoffregen/OneWire.git