name: Build IV-Zero
on: 
 - push
 - pull_request
jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: arduino/compile-sketches@v1
      with:
        sketch-paths: |
         - ./
        platforms: |
          - source-url: https://mcudude.github.io/MiniCore/package_MCUdude_MiniCore_index.json
            name: MiniCore:avr
        fqbn: "MiniCore:avr:48:clock=16MHz_external"
        libraries: |
          - name: OneWire
          - source-url: https://github.com/PaulStoffregen/OneWire.git